/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Controller.FuncionarioController;
import Model.Funcionario;
import java.awt.event.KeyEvent;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import utils.Utils;

/**
 *
 * @author aluno.saolucas
 */
public class FrAlterarFuncionario extends javax.swing.JDialog {

    private int idFuncionario;

    /**
     * Creates new form AlterarFuncionario
     */
    public FrAlterarFuncionario(java.awt.Frame parent, boolean modal, int idFuncionario) {
        super(parent, modal);
        initComponents();

        this.idFuncionario = idFuncionario;
        carregarFuncionario();
        this.setLocationRelativeTo(null);

    }

    public void carregarFuncionario() {

        FuncionarioController controller = new FuncionarioController();
        Funcionario funcionario = controller.buscarPorIdFuncionario(idFuncionario);

        String codigo = String.valueOf(funcionario.getIdFuncionario());
        edtCodigo.setText(codigo);
        edtCargo.setText(funcionario.getCargo());
        edtNome.setText(funcionario.getNome());
        edtEmail.setText(funcionario.getEmail());
        edtCpf.setText(funcionario.getCpf());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        edtCargo = new javax.swing.JTextField();
        edtNome = new javax.swing.JTextField();
        edtEmail = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        edtSenha = new javax.swing.JPasswordField();
        lblConfirmSenha = new javax.swing.JLabel();
        lblCPF = new javax.swing.JLabel();
        edtConfirmSenha = new javax.swing.JPasswordField();
        edtCpf = new javax.swing.JTextField();
        btnVoltar2 = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        edtCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblCargo = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alterar Funcionário");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(edtCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 108, 30));
        getContentPane().add(edtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 487, 43));

        edtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtEmailActionPerformed(evt);
            }
        });
        getContentPane().add(edtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 278, 487, 43));

        lblEmail.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblEmail.setText("Novo E-mail:");
        getContentPane().add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 253, -1, -1));

        lblNome.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNome.setText("Novo Nome:");
        getContentPane().add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        lblSenha.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblSenha.setText("Nova Senha:");
        getContentPane().add(lblSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 327, -1, -1));
        getContentPane().add(edtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 352, 487, 43));

        lblConfirmSenha.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblConfirmSenha.setText("Confirmar Nova Senha:");
        getContentPane().add(lblConfirmSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 413, -1, -1));

        lblCPF.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCPF.setText("Novo CPF:");
        getContentPane().add(lblCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 492, -1, -1));
        getContentPane().add(edtConfirmSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 438, 487, 43));

        edtCpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edtCpfKeyPressed(evt);
            }
        });
        getContentPane().add(edtCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 522, 487, 47));

        btnVoltar2.setBackground(new java.awt.Color(255, 0, 51));
        btnVoltar2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnVoltar2.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltar2.setText("Voltar");
        btnVoltar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVoltar2MouseClicked(evt);
            }
        });
        btnVoltar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltar2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 597, 134, 39));

        btnCadastrar.setBackground(new java.awt.Color(51, 153, 255));
        btnCadastrar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadastrarMouseClicked(evt);
            }
        });
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        btnCadastrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCadastrarKeyPressed(evt);
            }
        });
        getContentPane().add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 597, 134, 39));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Footlight MT Light", 1, 30)); // NOI18N
        jLabel1.setText("Alterar Funcionário");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 400, -1));

        jLabel2.setFont(new java.awt.Font("Footlight MT Light", 1, 24)); // NOI18N
        jLabel2.setText("NeuroMarket");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LoginFuncionario.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        edtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtCodigoActionPerformed(evt);
            }
        });
        jPanel1.add(edtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 60, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Código:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblCargo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCargo.setText("Cargo:");
        getContentPane().add(lblCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtEmailActionPerformed

    private void edtCpfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtCpfKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            gravar();
        }
    }//GEN-LAST:event_edtCpfKeyPressed

    private void btnVoltar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltar2MouseClicked
        this.dispose();
    }//GEN-LAST:event_btnVoltar2MouseClicked

    private void btnVoltar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVoltar2ActionPerformed

    private void btnCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarMouseClicked
        if (verificarCampos()) {

            gravar();
        }
    }//GEN-LAST:event_btnCadastrarMouseClicked

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnCadastrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCadastrarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            gravar();
        }
    }//GEN-LAST:event_btnCadastrarKeyPressed

    private void edtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtCodigoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        URL caminhoImagem = getClass().getResource("/images/logoMercado2.png");

        ImageIcon icon = new ImageIcon(caminhoImagem);

        // Define o ícone da janela
        this.setIconImage(icon.getImage());
    }//GEN-LAST:event_formWindowOpened

    public boolean verificarCampos() {
        if (edtNome.getText().equals("")) {
            JOptionPane.showMessageDialog(null,
                    "O campo 'Nome' em branco");
            return false;
        }

        if (!edtNome.getText().matches("^[\\p{L} ]+$")) {
            JOptionPane.showMessageDialog(null,
                    "O campo 'Nome' possui caracteres inválidos");
            return false;
        }

        if (edtEmail.getText().equals("")) {
            JOptionPane.showMessageDialog(null,
                    "O campo 'Email' em branco");
            return false;
        }
        if (!edtEmail.getText().matches(
                "^[a-z0-9._-]+@[a-z._]+.[a-z._]+$")) {
            JOptionPane.showMessageDialog(null,
                    "O campo 'Email' possui formato inválido");
            return false;
        }

        if (edtSenha.isEditable()) {
            String senha = new String(edtSenha.getPassword());

            if (senha.length() < 6) {
                JOptionPane.showMessageDialog(null,
                        "O campo 'Senha' deve ser maior que 8 caracteres");
                return false;
            }

            if (!senha.equals(new String(edtConfirmSenha.getPassword()))) {
                JOptionPane.showMessageDialog(null,
                        "As senhas não são iguais");
                return false;
            }
            if (!edtCpf.getText().matches("^[0-9]{3}.[0-9]{3}.[0-9]{3}-[0-9]{2}")) {//a-
                JOptionPane.showMessageDialog(null,
                        "O campo 'Nome' possui formato inválido");
                return false;
            }
        }

        return true;
    }

    public void gravar() {
        Funcionario funcionario = new Funcionario();

        funcionario.setIdFuncionario(idFuncionario);
        funcionario.setNome(edtNome.getText());
        funcionario.setEmail(edtEmail.getText());
        funcionario.setCpf(edtCpf.getText());
        funcionario.setCargo(edtCargo.getText());

        if (edtSenha.isEditable()) {
            String senha = new String(edtSenha.getPassword());
            String senhaHash = Utils.calcularHash(senha);
            funcionario.setSenha(senhaHash);
        }

        FuncionarioController controller = new FuncionarioController();

        if (controller.alterarFuncionario(funcionario)) {
            JOptionPane.showMessageDialog(null,
                    "funcionario: " + funcionario.getNome()
                    + " alterado com sucesso!");
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null,
                    "funcionario não será alterado!");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrAlterarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrAlterarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrAlterarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrAlterarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrAlterarFuncionario dialog = new FrAlterarFuncionario(new javax.swing.JFrame(), true, 0);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnVoltar2;
    private javax.swing.JTextField edtCargo;
    private javax.swing.JTextField edtCodigo;
    private javax.swing.JPasswordField edtConfirmSenha;
    private javax.swing.JTextField edtCpf;
    private javax.swing.JTextField edtEmail;
    private javax.swing.JTextField edtNome;
    private javax.swing.JPasswordField edtSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblConfirmSenha;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSenha;
    // End of variables declaration//GEN-END:variables
}
